"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.appRouterV1 = void 0;
const controllers_1 = require("../../controllers");
const user_router_1 = require("./user-router");
const upload_file_route_1 = require("./upload-file-route");
const productRouter_1 = require("./productRouter");
const orderRouter_1 = require("./orderRouter");
const addressRouter_1 = require("./addressRouter");
const transactionRoutes_1 = require("./transactionRoutes");
const statisticRouter_1 = require("./statisticRouter");
const cartRouter_1 = require("./cartRouter");
const settingRouter_1 = require("./settingRouter");
const notificationRouter_1 = require("./notificationRouter");
const myAddressRouter_1 = require("./myAddressRouter");
const adminRouter_1 = require("./adminRouter");
const waBlasSettingRouter_1 = require("./waBlasSettingRouter");
const twilioSettingRouter_1 = require("./twilioSettingRouter");
const waBlasRouter_1 = require("./waBlasRouter");
const bankSettingRouter_1 = require("./bankSettingRouter");
const myProfileRouter_1 = require("./myProfileRouter");
const category1Router_1 = require("./category1Router");
const category2Router_1 = require("./category2Router");
const category3Router_1 = require("./category3Router");
const appRouterV1 = (app) => {
    app.get('/api/v1', async (req, res) => await (0, controllers_1.index)(req, res));
    (0, upload_file_route_1.uploadFileRoutes)(app);
    (0, adminRouter_1.adminRouter)(app);
    (0, user_router_1.userRoutes)(app);
    (0, productRouter_1.productRoutes)(app);
    (0, orderRouter_1.orderRoutes)(app);
    (0, category1Router_1.category1Routes)(app);
    (0, category2Router_1.category2Routes)(app);
    (0, category3Router_1.category3Routes)(app);
    (0, addressRouter_1.addressRoutes)(app);
    (0, myAddressRouter_1.myAddressRoutes)(app);
    (0, myProfileRouter_1.myProfileRouter)(app);
    (0, transactionRoutes_1.transactionRoutes)(app);
    (0, statisticRouter_1.statisticRouters)(app);
    (0, cartRouter_1.cartRoutes)(app);
    (0, settingRouter_1.settingRouters)(app);
    (0, notificationRouter_1.notificationRoutes)(app);
    (0, waBlasSettingRouter_1.waBlasSettingRouter)(app);
    (0, waBlasRouter_1.waBlasRouter)(app);
    (0, twilioSettingRouter_1.twilioSettingRouter)(app);
    (0, bankSettingRouter_1.bankSettingRouter)(app);
};
exports.appRouterV1 = appRouterV1;
